config/routes.rb
Osb::Application.routes.draw do

  resources :open_spaces do
    resources :tracks
  end

  devise_for :admins

  devise_for :users

  root :to => "welcome#index"

end

app/models/admin.rb
class Admin

  include DataMapper::Resource
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  property :id, Serial


end

app/models/open_space.rb
class OpenSpace

  include DataMapper::Resource

  property :id, Serial

  property :title, String
  property :location, String
  property :start, DateTime
  property :end, DateTime
  property :allDay, Boolean

  belongs_to :user
  
  has n, :tracks

  def each_day
    Range.new(self.start, self.end).each { |day|
      yield day
    }
  end

end

app/models/track.rb
class Track

  include DataMapper::Resource

  property :id, Serial

  property :name, String
  property :location, String
  property :position, Integer
  
  belongs_to :open_space

end

app/models/user.rb
class User

  include DataMapper::Resource
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :token_authenticatable, :lockable

  property :firstname, String, :required => true
  property :lastname, String, :required => true


  property :id, Serial

  has n, :open_spaces

  def fullname
    "%s %s" % [self.firstname, self.lastname]
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/open_spaces_controller.rb
class OpenSpacesController < ApplicationController
  before_filter :authenticate_user!
  layout false
  # GET /open_spaces
  # GET /open_spaces.xml
  def index
    startdate = Time.at(params[:start].to_i) || 0
    enddate = Time.at(params[:end].to_i) 
    enddate = Time.now + 5.years if startdate == enddate 
    @open_spaces = current_user.open_spaces.all(:start.gte => startdate, :end.lte => enddate)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @open_spaces }
      format.json { render :json => @open_spaces }
    end
  end

  # GET /open_spaces/1
  # GET /open_spaces/1.xml
  def show
    @open_space = current_user.open_spaces.get(params[:id])

    respond_to do |format|
      if (@open_space) then
        format.html { render :layout => 'application' }
        format.xml  { render :xml => @open_space }
        format.json { render :json => @open_space }
      else
        format.html { render :text => "No such object", :status => 404}
        format.xml  { render :xml => @open_space }
        format.json { render :json => @open_space }
      end
    end
  end

  # GET /open_spaces/new
  # GET /open_spaces/new.xml
  def new
    @open_space = current_user.open_spaces.new

    respond_to do |format|
      format.html { render :layout => false }# new.html.erb
      format.xml  { render :xml => @open_space }
    end
  end

  # GET /open_spaces/1/edit
  def edit
    @open_space = current_user.open_spaces.get(params[:id])
    respond_to do |format|
      if (@open_space) then
        format.html # edit.html.erb
        format.xml  { render :xml => @open_space }
        format.json { render :json => @open_space }
      else
        format.html { render :text => "No such object", :status => 404}
        format.xml  { render :xml => @open_space }
        format.json { render :json => @open_space }
      end
    end
  end

  # POST /open_spaces
  # POST /open_spaces.xml
  def create
    @open_space = current_user.open_spaces.new(params[:open_space])

    respond_to do |format|
      if (@open_space && @open_space.save)
        format.html { redirect_to(@open_space, :notice => 'Open space was successfully created.') }
        format.xml  { render :xml => @open_space, :status => :created, :location => @open_space }
        format.js   
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @open_space.errors, :status => :unprocessable_entity }
        format.js   { render :json => @open_space.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /open_spaces/1
  # PUT /open_spaces/1.xml
  def update
    @open_space = current_user.open_spaces.get(params[:id])

    respond_to do |format|
      if @open_space.update(params[:open_space])
        format.html { redirect_to(@open_space, :notice => 'Open space was successfully updated.') }
        format.xml  { head :ok }
        format.js   
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @open_space.errors, :status => :unprocessable_entity }
        format.js   { render :json => @open_space.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /open_spaces/1
  # DELETE /open_spaces/1.xml
  def destroy
    @open_space = current_user.open_spaces.get(params[:id])
    @open_space.destroy

    respond_to do |format|
      format.html { redirect_to(open_spaces_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/original_template_controller.rb
class OriginalTemplateController < ApplicationController
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  # GET /tracks
  # GET /tracks.xml
  def index
    @tracks = Track.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tracks }
    end
  end

  # GET /tracks/1
  # GET /tracks/1.xml
  def show
    @track = Track.get(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @track }
    end
  end

  # GET /tracks/new
  # GET /tracks/new.xml
  def new
    @open_space = current_user.open_spaces.get(params[:open_space_id])
    @track = @open_space.tracks.new

    respond_to do |format|
      format.html { render :layout => false }
      format.xml  { render :xml => @track }
    end
  end

  # GET /tracks/1/edit
  def edit
    @track = Track.get(params[:id])
  end

  # POST /tracks
  # POST /tracks.xml
  def create

    @open_space = current_user.open_spaces.get(params[:open_space_id])
    @track = @open_space.tracks.new(params[:track])

    respond_to do |format|
      if @track.save
        format.html { redirect_to(@track, :notice => 'Track was successfully created.') }
        format.xml  { render :xml => @track, :status => :created, :location => @track }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @track.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tracks/1
  # PUT /tracks/1.xml
  def update
    @track = Track.get(params[:id])

    respond_to do |format|
      if @track.update(params[:track])
        format.html { redirect_to(@track, :notice => 'Track was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @track.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.xml
  def destroy
    @track = Track.get(params[:id])
    @track.destroy

    respond_to do |format|
      format.html { redirect_to(tracks_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :authenticate_user!
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/open_spaces_helper.rb
module OpenSpacesHelper
end

app/helpers/template_helper.rb
module TemplateHelper
  def render_or_default(partial, default = partial)
    render :partial => partial
  rescue ActionView::MissingTemplate
    begin
      render :partial => "layouts/#{default}"
    rescue ActionView::MissingTemplate
      nil
    end
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_menu.html.erb
<ul>
  <%= content_tag("li", :class => (current_page?(:controller => '/welcome', :action => 'index') ? 'active': nil) ) do -%>
    <%= link_to " home", root_url %>
  <% end -%>
  <%= content_tag("li", :class => (current_page?(:controller => '/open_spaces', :action => 'new') ? 'active': nil) ) do -%>
    <%= link_to " new openspace", new_open_space_url %>
  <% end -%>
  <li><a href="/about"> about</a></li>
  <li><a href="/inquiry/new"> contact </a></li>
  <% if user_signed_in? %>
    <li><%= link_to "sign out", destroy_user_session_url %></li>
  <% else %>
  <%= content_tag("li", :class => (current_page?(:action=>"new", :controller=>"devise/sessions") ? 'active': nil) ) do -%>
    <%= link_to " sign in", new_user_session_url %>
  <% end -%>
  <% end %>
</ul>

app/views/layouts/_sidebar.html.erb
<ul>
			<li>
				<h2><b>Lorem</b> Ipsum</h2>
				<ul>
					<li><a href="#x">Fusce dui neque fringilla</a></li>
					<li><a href="#">Eget tempor eget nonummy</a></li>
					<li><a href="#">Magna lacus bibendum mauris</a></li>
					<li><a href="#">Nec metus sed donec</a></li>
					<li><a href="#">Magna lacus bibendum mauris</a></li>
					<li><a href="#">Velit semper nisi molestie</a></li>
					<li><a href="#">Eget tempor eget nonummy</a></li>
				</ul>
			</li>
			<li>
				<h2><b>Volutpat</b> Dolore</h2>
				<ul>
					<li><a href="#">Nec metus sed donec</a></li>
					<li><a href="#">Magna lacus bibendum mauris</a></li>
					<li><a href="#">Velit semper nisi molestie</a></li>
					<li><a href="#">Eget tempor eget nonummy</a></li>
					<li><a href="#">Nec metus sed donec</a></li>
					<li><a href="#">Magna lacus bibendum mauris</a></li>
					<li><a href="#">Velit semper nisi molestie</a></li>
				</ul>
			</li>
		</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--

Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 2.5 License

Title      : StandardIssue
Version    : 1.0
Released   : 20070723
Description: A two-column, fixed-width and lightweight template ideal for 1024x768 resolutions. Suitable for blogs and small websites.

-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>OpenSpace Board</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="/stylesheets/default.css" rel="stylesheet" type="text/css" />
<link href="/stylesheets/fullcalendar.css" rel="stylesheet" type="text/css" />
<%= stylesheet_link_tag 'custom-theme/jquery-ui-1.8.7.custom.css' %>
<%= stylesheet_link_tag 'extras.css' %>
<%= javascript_include_tag 'date.format.js' %>
<%= javascript_include_tag 'jquery.js' %>
<%= javascript_include_tag 'jquery-ui.js' %>
<%= javascript_include_tag 'rails.js' %>
<%= javascript_include_tag 'fullcalendar.js' %>
<%= javascript_include_tag 'jquery.qtip-1.0.0-rc3.min.js' %>
<%= javascript_include_tag 'application.js' %>
<%= yield(:head) %>
</head>
<body>
<!-- start header -->
<div id="header">
	<div id="logo">
		<h1><a href="/">OpenSpace Board</a></h1>
    <h2><a href="http://www.dieprojektur.com/">By Die Projektur GmbH</a></h2>
	</div>
	<div id="menu"><%= render_or_default('menu') %></div>
</div>
<!-- end header -->
<!-- start page -->
<div id="page">
	<!-- start content -->
	<div id="content"><%= yield %></div>
	<!-- end content -->
	<!-- start sidebar -->
  <div id="sidebar"><%= render_or_default('sidebar') %></div>
	<!-- end sidebar -->
	<div style="clear: both;">&nbsp;</div>
</div>
<!-- end page -->
<!-- start footer -->
<div id="footer">
	<div class="wrap">
		<div id="fbox1" class="box2">
      <h2><%= link_to 'Die Projektur', 'http://dieprojektur.com/'  %></h2>
    </div>
		<div id="fbox2" class="box2">
      <h2><%= link_to 'Go Agile ~ Go Scrum', 'http://www.scrum.cc/'  %></h2>
		</div>
		<div id="fbox3" class="box2">
			<h2><b>Metus</b> Nonummy</h2>
		</div>
	</div>
	<p id="legal">(c) 2010 dieprojektur GmbH. Design by <a href="http://www.nodethirtythree.com/">NodeThirtyThree</a> and <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>.</p>
</div>
<!-- end footer -->
</body>
</html>

app/views/open_spaces/_form.html.erb
<%= form_for(@open_space) do |f| %>
  <% if @open_space.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@open_space.errors.count, "error") %> prohibited this open_space from being saved:</h2>

      <ul>
      <% @open_space.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :start %><br />
    <%= text_field_tag 'open_space[start]', l(@open_space.start), :class => 'datepicker' if @open_space.start %>
    <%= f.text_field :start, :class => 'datepicker' unless @open_space.start %>
  </div>
  <div class="field">
    <%= f.label :end %><br />
    <%= text_field_tag 'open_space[end]', l(@open_space.end), :class => 'datepicker' if @open_space.end %>
    <%= f.text_field :end, :class => 'datepicker' unless @open_space.end %>
  </div>
  <div class="field">
    <%= f.check_box :allDay %>
    <%= f.label :allDay, 'All Day?' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/open_spaces/create.js.erb
$("#info_area").html("Item successfully created");
$("#dialog").dialog("destroy");
$("#calendar").fullCalendar('refetchEvents');

app/views/open_spaces/edit.html.erb
<%= render 'form' %>

app/views/open_spaces/index.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th>Starts on</th>
    <th>Ends on</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @open_spaces.each do |open_space| %>
  <tr>
    <td><%= open_space.title %></td>
    <td><%= open_space.location %></td>
    <td><%= open_space.start %></td>
    <td><%= open_space.end %></td>
    <td><%= link_to 'Show', open_space %></td>
    <td><%= link_to 'Edit', edit_open_space_path(open_space) %></td>
    <td><%= link_to 'Destroy', open_space, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Open space', new_open_space_path %>

app/views/open_spaces/new.html.erb
<%= render 'form' %>

app/views/open_spaces/show.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'open_spaces.js' %>
<% end -%>
<ul class="pmenu">
  <li><b>Title</b>: <%= @open_space.title -%></li>
  <li><b>Location</b>: <%= @open_space.location -%></li>
  <li><b>Start</b>: <%= l @open_space.start, :format => :date -%></li>
  <li><b>End</b>: <%= l @open_space.end, :format => :date -%></li>
</ul>

<div id="trackmenu">
  <button data-url-newtrack="<%= new_open_space_track_url(@open_space) %>">Add Track</button>
</div>
<div id="tabs">
  <ul id="daytabs">
    <% @open_space.each_day do |day| %>
      <% daystr = day.strftime("%Y-%d-%m") %>
      <%= content_tag("li", link_to(day.strftime("%A"), "#day_#{daystr}"))%>
    <% end -%>
  </ul>
    <% @open_space.each_day do |day| %>
      <% daystr = day.strftime("%Y-%d-%m") %>
      <div id="day_<%= daystr %>">
        <h2>Tracks:</h2>
        <% @open_space.tracks.each do |track| %>
          <div id="track_<%= track.id %>" class="tracks" data-track-id="<%= track.id %>" data-day="<%= day.strftime("%Y-%m-%d") %>" data-os-id="<%= @openspace.id %>">
            <h2><%= track.title %></h2>

          </div>
        <% end -%>
      </div>
    <% end -%>
</div>
<div id="dialog"></div>

app/views/open_spaces/update.js.erb
$("#info_area").html("Item successfully updated");
$("#dialog").dialog("destroy");
$("#calendar").fullCalendar('refetchEvents');

app/views/original_template/index.html.erb
<p>You are using named yields. Here are examples how to use them:</p>
<% content_for :head do -%>
  <script></script>
<% end -%>
<% content_for :menu do -%>
  
		<ul>
			<li class="active"><a href="#"> home</a></li>
			<li><a href="#">photos</a></li>
			<li><a href="#">about</a></li>
			<li><a href="#">links</a></li>
			<li><a href="#">contact </a></li>
		</ul>
	
<% end -%>

<% content_for :sidebar do -%>
  
		<ul>
			<li id="search">
				<h2><b>Search</b></h2>
				<form method="get" action="">
					<fieldset>
					<input type="text" id="s" name="s" value="" />
					<input type="submit" id="x" value="Search" />
					</fieldset>
				</form>
			</li>
			<li>
				<h2><b>Lorem</b> Ipsum</h2>
				<ul>
					<li><a href="#">Fusce dui neque fringilla</a></li>
					<li><a href="#">Eget tempor eget nonummy</a></li>
					<li><a href="#">Magna lacus bibendum mauris</a></li>
					<li><a href="#">Nec metus sed donec</a></li>
					<li><a href="#">Magna lacus bibendum mauris</a></li>
					<li><a href="#">Velit semper nisi molestie</a></li>
					<li><a href="#">Eget tempor eget nonummy</a></li>
				</ul>
			</li>
			<li>
				<h2><b>Volutpat</b> Dolore</h2>
				<ul>
					<li><a href="#">Nec metus sed donec</a></li>
					<li><a href="#">Magna lacus bibendum mauris</a></li>
					<li><a href="#">Velit semper nisi molestie</a></li>
					<li><a href="#">Eget tempor eget nonummy</a></li>
					<li><a href="#">Nec metus sed donec</a></li>
					<li><a href="#">Magna lacus bibendum mauris</a></li>
					<li><a href="#">Velit semper nisi molestie</a></li>
				</ul>
			</li>
		</ul>
	
<% end -%>



<!-- original body content -->
		<div class="box1">
			<p><img src="/images/img04.jpg" alt="" width="74" height="79" class="left" /><strong>Volutpat at varius</strong> sed sollicitudin et, arcu. Vivamus viverra. Nullam turpis. Vestibulum eros. Cras lobortis <a href="#">eget nonummy</a>. Vestibulum vel purus. In eget odio in sapien adipiscing sed blandit. Quisque augue tortor, facilisis sit amet, aliquam.</p>
		</div>
		<div class="post">
			<h1 class="title">Welcome to StandardIssue 1.0</h1>
			<div class="entry">
				<p>This is StandardIssue 1.0, a free, fully standards-compliant CSS template designed by <a href="http://www.nodethirtythree.com/">NodeThirtyThree</a> for <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>. This free template is released under a <a href="http://creativecommons.org/licenses/by/2.5/">Creative Commons Attributions 2.5</a> license, so you’re pretty much free to do whatever you want with it (even use it commercially) provided you keep the links in the footer intact. Aside from that, have fun with it :)</p>
				<p>Be sure to check out some of my commercial work over at <a href="http://www.4templates.com/?aff=nodethirtythree">4Templates</a>. This template is also available as a <a href="http://www.freewpthemes.net/preview/standardissue/">WordPress theme</a> at <a href="http://www.freewpthemes.net/">Free WordPress Themes</a>.</p>
			</div>
			<div class="meta">
				<p class="byline">Posted on July 21, 2007 by NodeThirtyThree</p>
				<p class="links"><a href="#" class="more">Read full article</a> <b>|</b> <a href="#" class="comments">Comments (32)</a></p>
			</div>
		</div>
		<div class="post">
			<h2 class="title">Lorem Ipsum Dolor Volutpat</h2>
			<div class="entry">
				<p>Curabitur tellus. Phasellus tellus turpis, iaculis in, faucibus lobortis, posuere in, lorem. Donec a ante. Donec neque purus, adipiscing id, eleifend a, cursus vel, odio. Vivamus varius justo sit amet leo. Morbi sed libero. Vestibulum blandit augue at mi. Praesent fermentum lectus eget diam. Nam cursus, orci sit amet porttitor iaculis, ipsum massa aliquet nulla, non elementum mi elit a mauris. In hac habitasse platea.</p>
			</div>
			<div class="meta">
				<p class="byline">Posted on July 18, 2007 by NodeThirtyThree</p>
				<p class="links"><a href="#" class="more">Read full article</a> <b>|</b> <a href="#" class="comments">Comments (32)</a></p>
			</div>
		</div>
	

app/views/tracks/_form.html.erb
<%= form_for([@open_space, @track]) do |f| %>
  <% if @track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
      <% @track.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tracks/edit.html.erb
<h1>Editing track</h1>

<%= render 'form' %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

app/views/tracks/index.html.erb
<h1>Listing tracks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th>Position</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tracks.each do |track| %>
  <tr>
    <td><%= track.name %></td>
    <td><%= track.location %></td>
    <td><%= track.position %></td>
    <td><%= link_to 'Show', track %></td>
    <td><%= link_to 'Edit', edit_track_path(track) %></td>
    <td><%= link_to 'Destroy', track, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Track', new_track_path %>

app/views/tracks/new.html.erb
<h1>New track</h1>

<%= render 'form' %>

app/views/tracks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @track.name %>
</p>

<p>
  <b>Location:</b>
  <%= @track.location %>
</p>

<p>
  <b>Position:</b>
  <%= @track.position %>
</p>


<%= link_to 'Edit', edit_track_path(@track) %> |
<%= link_to 'Back', tracks_path %>

app/views/welcome/index.html.erb
<h1>Welcome, <%= current_user.fullname %></h1>
<h2>Overview over your Open Spaces:</h2>

<div id="info_area"></div>
<div id="dialog"></div>
<div id="calendar">
</div>